kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: aks-cluster-readonly-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aks-cluster-readonly-role # Name of the associated cluster role definition.
subjects:
- kind: Group
  name: "9b39b811-512f-488f-8002-8dced722d6fa" # groupObjectId of Azure AD Group (aksreadonly)
