apiVersion: apps/v1
kind: Deployment 
metadata:
  name: usermgmt-webapp
  labels:
    app: usermgmt-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usermgmt-webapp
  template:  
    metadata:
      labels: 
        app: usermgmt-webapp
    spec:
      initContainers:
        - name: init-db
          image: busybox:1.31
          command: ['sh', '-c', 'echo -e "Checking for the availability of MySQL Server deployment"; while ! nc -z mysql 3306; do sleep 1; printf "-"; done; echo -e "  >> MySQL DB Server has started";']      
      containers:
        - name: usermgmt-webapp
          image: stacksimplify/kube-usermgmt-webapp:1.0.0-MySQLDB
          imagePullPolicy: Always
          ports: 
            - containerPort: 8080
          env:
            - name: DB_HOSTNAME
              value: "mysql" # Matches the ExternalName service name.
            - name: DB_PORT
              value: "3306"            
            - name: DB_NAME
              value: "webappdb" # Name of the DB you created on Azure MySql server.
            - name: DB_USERNAME
              value: "dbadmin@akswebappdb01" # Copy and paste from Azure MySql overview.
            - name: DB_PASSWORD
              value: "Redhat1449" # MySql Server password used at the time of creation.
