apiVersion: v1
kind: Service
metadata:
  name: usermgmt-webapp-service
  labels: 
    app: usermgmt-webapp
spec:
  type: LoadBalancer
  selector:
    app: usermgmt-webapp # Matches the pod name given in the deployment.
  ports: 
    - port: 80
      targetPort: 8080

